name: Code Quality & Tests

on: push

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  tests:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
          - runner: macos-13
          - runner: macos-14
          - runner: windows-latest

    steps:
      - uses: actions/checkout@v4
      - id: uv
        uses: ./.github/actions/set-up-uv

      - name: Tests
        run: uv run nox

      - name: Minimize uv cache
        run: uv cache prune --ci
